name: Build and deploy to CAR-RestBottle

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: CAR-RestBottle
  AZURE_WEBAPP_PACKAGE_PATH: BicycleDevOps/publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 10.0.x

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore BicycleDevOps.slnx

      - name: Build
        run: dotnet build BicycleDevOps.slnx --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test BicycleDevOps.slnx --configuration ${{ env.CONFIGURATION }} --no-build

      - name: Publish
        run: dotnet publish BicycleDevOps/BicycleDevOps.csproj --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CAR_RestBottle_CLIENT_ID_F324 }}
          tenant-id: ${{ vars.CAR_RestBottle_TENANT_ID_4EFF }}
          subscription-id: ${{ vars.CAR_RestBottle_SUBSCRIPTION_ID_4EFF }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}